apiVersion: v1
kind: Namespace
metadata:
  name: payment
  labels:
    app.kubernetes.io/part-of: payment-vault-platform
    pod-security.kubernetes.io/enforce: baseline # Bật Pod Security Standards ở mức baseline
