apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-app-sa
  namespace: payment
  annotations:
    # 🛡️ IRSA: Cầu nối gán IAM Role trên AWS vào ServiceAccount trong Kubernetes
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/PaymentAppSecretReaderRole
