apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-vault.fullname" . }}
  labels:
    {{- include "payment-vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "payment-vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "payment-vault.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      
      # 🛡️ CIS Benchmarks: Cấm chạy quyền root
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP

        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}

        # Nạp biến môi trường thông thường
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}

        # 🛡️ Tích hợp Secret từ External Secrets Operator (Lab 11)
        {{- if .Values.secretRef.enabled }}
        envFrom:
        - secretRef:
            name: {{ .Values.secretRef.name }}
        {{- end }}

        # 🛡️ Giám sát sức khỏe phục vụ ArgoCD
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: http
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: http
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
