apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-db-external-secret
  namespace: payment
spec:
  refreshInterval: "1h" # Tự động kiểm tra thay đổi trên AWS mỗi 1 giờ để hỗ trợ Rotation
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: payment-db-secret # Tên của K8s Secret được ESO tự động tạo ra
    creationPolicy: Owner   # Nếu ExternalSecret bị xóa, K8s Secret này cũng tự động bị xóa theo
  dataFrom:
  - extract:
      key: /prod/payment/db-credentials # Tên Secret trên AWS Secrets Manager
