apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-api-sa
  namespace: ecommerce
  annotations:
    # Zero-Trust IRSA: IAM Role ARN do Terraform khởi tạo trên Floci
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/ecommerce-prod-eks-nodes-role
  labels:
    app.kubernetes.io/name: order-api
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-worker-sa
  namespace: ecommerce
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/ecommerce-prod-eks-nodes-role
  labels:
    app.kubernetes.io/name: order-worker
    app.kubernetes.io/component: worker
