apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-backend-sa
  namespace: production-ecommerce
  annotations:
    # ARN lấy từ output của terraform (sau này apply thật sẽ dùng ARN thật)
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/ecommerce-backend-irsa-prod"
