apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-app-sa
  namespace: order-app
  annotations:
    # Sau này thay ARN thực tế từ output của terraform
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/order-irsa-dev"
