apiVersion: v1
kind: Secret
metadata:
  name: order-tls-secret
  namespace: order-app
type: kubernetes.io/tls
data:
  # Base64 của file certificate (tls.crt)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg== 
  # Base64 của private key (tls.key)
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCg==
